name: OWASP ZAP Baseline Scan

# This workflow will trigger on a push to any branch and on pull requests to main
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'https://juice-shop.herokuapp.com/#'